Vagrant.configure("2") do |config|
  config.vm.define "bacula" do |bacula|
    bacula.vm.box = "centos/7"
    bacula.vm.hostname = "bacula"
    bacula.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    bacula.vm.network "private_network", ip: "192.168.11.101"
    bacula.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    bacula.vm.provision :ansible do |ansible|
      ansible.playbook = "bacula_server.yml"
    end
  end
  config.vm.define "client" do |client|
    client.vm.box = "centos/7"
    client.vm.hostname = "client"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    client.vm.network "private_network", ip: "192.168.11.102"
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    client.vm.provision :ansible do |ansible|
      ansible.playbook = "bacula_client.yml"
    end
  end
end
