# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :Router1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net-2"},
                   {ip: '192.168.3.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net-3"},
                   {ip: '10.10.1.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net-r1"},
                ]
  },
  :Router2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net-2"},
                   {ip: '192.168.4.2', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net-4"},
                   {ip: '10.10.2.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net-r2"},
                ]
  },
  :Router3 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.3.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "net-3"},
                   {ip: '192.168.4.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "net-4"},
                   {ip: '10.10.3.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "net-r3"},
                ]
  },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s

            boxconfig[:net].each do |ipconf|
            box.vm.network "private_network", ipconf
            end
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "512"]
            end        
            if boxconfig.key?(:public)
            box.vm.network "public_network", boxconfig[:public]
            end

            box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
                    cp ~vagrant/.ssh/auth* ~root/.ssh
            SHELL
            
            case boxname.to_s
                when "Router1"
                box.vm.provision :ansible do |ansible|
                  ansible.playbook = "router1.yml"
                end
                when "Router2"
                box.vm.provision :ansible do |ansible|
                  ansible.playbook = "router2.yml"
                end
                when "Router3"
                box.vm.provision :ansible do |ansible|
                  ansible.playbook = "router3.yml"
                end
            end
        end
    end
end
