Vagrant.configure("2") do |config|
  config.vm.define "freeipa" do |freeipa|
    freeipa.vm.box = "centos/7"
    freeipa.vm.hostname = "freeipa.example.local"
    freeipa.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
    end
    freeipa.vm.network "private_network", ip: "192.168.11.101", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "freeipa-net"
    freeipa.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    freeipa.vm.provision :ansible do |ansible|
      ansible.playbook = "freeipa.yml"
    end
  end
  config.vm.define "client" do |client|
    client.vm.box = "centos/7"
    client.vm.hostname = "client.example.local"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    client.vm.network "private_network", ip: "192.168.11.102", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "freeipa-net"
    client.vm.provision "shell", inline: <<-SHELL
      mkdir -p ~root/.ssh
      cp ~vagrant/.ssh/auth* ~root/.ssh
    SHELL
    client.vm.provision :ansible do |ansible|
      ansible.playbook = "client.yml"
    end
  end
end

